### ISSUE TITLE
Tab through arguments

### ISSUE THREAD

**Issue by florian-wagner** [spadarian/docblock-python#1]
Hey Jose,

first of all, thank you so much for doing this. That's the one thing I've been missing after moving from vim to atom.

It would be great if one can tab through the arguments like you can do in https://atom.io/packages/docblockr or UltiSnips, but I have no idea how hard it would be to implement this.

**Comment by spadarian** [comment]
No worries. Sorry for the delay, but my PhD is keeping me busy.

To be honest, I'm not sure how difficult it would be to do that. I will have a look at those packages, but I can't promise anything.
