### ISSUE TITLE
Adopt eslint

### ISSUE THREAD

**Issue by SKalt** [spadarian/docblock-python#10]
I was looking into another issue and noticed this project does not use [eslint](https://eslint.org/docs/about/).  Adopting a linter would make contributing to this project easier by making the code more consistent and giving a clear set of rules to follow.  I'd vote using eslint-config-google and having [`husky`](https://www.npmjs.com/package/husky) enforce pre-commit linting/error correction.  @spadarian, let me know which rules you want and I'll set it up!

**Comment by spadarian** [comment]
#13 Fixed this issue
