### ISSUE TITLE
No Generation happening in Cython

### ISSUE THREAD

**Issue by SebastianSemper** [spadarian/docblock-python#27]
I get no output from docblock in a file named `foobar.pyx`, which is residing in a class definition. I am running `docblock 0.11`, `atom 1.32.2` and `electron 2.0.12` on Manjaro Linux. 

Hints?

```
cpdef tuple _getComplexity(self):
        cdef float complexityFwd = self.numRows
        cdef float complexityBwd = self.numCols
        cdef Matrix item
        for item in self:
            complexityFwd += item.numRows + item.numCols
            complexityBwd += item.numCols + item.numRows

        return (complexityFwd, complexityBwd)
```

**Comment by spadarian** [comment]
I forgot about the extension...
Are you using the `language-cython` package?

**Comment by SebastianSemper** [comment]
Yes, I do. Normal *.py process fine btw. this was a false alarm from my
side.

**Comment by spadarian** [comment]
Ok... the solution is simple then.
I just need to add support or the Cython language.
I will push a patch in a few minutes.
