### ISSUE TITLE
parametrize the tab length

### ISSUE THREAD

**Issue by SKalt** [spadarian/docblock-python#32]
See https://github.com/google/yapf/blob/master/CONTRIBUTING.rst#yapf-coding-style: they use two spaces for indentation rather than four spaces.  Grabbing the current editor tab spacing would handle this (admittedly heretical) use-case.

<details open>
Generally where the change would be made: https://github.com/spadarian/docblock-python/blob/master/lib/docblock-python.js#L296

~`atom.config.scopedSettingsStore.cache['getPropertyValue:.source.python:editor.tabLength']` does grab the correct number of spaces, but there should be a better way to do it.~
`atom.config.get('editor.tabLength')` should do the trick.
</details>

**Comment by spadarian** [comment]
When I started writing the plugin I thought about that, and I guess it is time to implement it.
My initial idea was to add an option to change the sequence of characters used.

- 2 spaces
- 4 spaces
- tab (Do people still use `tab` to indent?)

Probably is a good idea to use the setting from the editor or `language-python`. Does `language-python` have priority over editor settings? When I try `atom.config.get('editor.tabLength')` in the console I get `2`... even if I use 4 spaces in Python.

**Comment by SKalt** [comment]
Could you try config.get(.souce.python.editor.tabLength)? If that doesn't
work, we might fall back in the section I crossed out, despite  the section
I crossed out: it has .source.python-specific settings, though it has an
awful access method.
