### ISSUE TITLE
[Feature request] Add a feature to blank out the default description

### ISSUE THREAD

**Issue by cvanelteren** [spadarian/docblock-python#34]
First of all, thanks for the extension I like the core idea. However during use I find myself having to do "too much work" to remove the default parameter description, I therefore propose to add an option to leave the link blank after the parameter type "Description of variable `whatever'".  Specifically change:

    def f(x = None) -> None:
        """Short summary.

        :param x: Description of parameter `x`. Defaults to None.
        :return: Description of returned object.

        """
        return x

To: 

    def f(x = None) -> None:
        """Short summary.

        :param x: . Defaults to None.
        :return:

        """
        return x

Edit: I tried playing around with the source js script but for some reason, it doesn't stick, I'll look at it later as well.

**Comment by spadarian** [comment]
Sure. Sounds like a reasonable idea.
I don't have much time the following weeks (conference) but I can review and potentially merge a PR.
