### ISSUE TITLE
Wrong indentation of sphinx style :return: and :raises:

### ISSUE THREAD

**Issue by oliver-joos** [spadarian/docblock-python#36]
docblock-python is really helpful, many thanks to spadarian!

I have a problem with indentation: if I choose style "sphinx" (and all checkboxes enabled) the lines with :return: are not indented at all, and :raises: are always indented 4 spaces, even if the doc comment starts more indented. The rest of the lines are ok.

Example: [docblock-bug_sphinx-indent.txt](https://github.com/spadarian/docblock-python/files/3573659/docblock-bug_sphinx-indent.txt)

I tried to fix it by editing lib/templates.js, but did not succeed yet.
Am I doing something wrong? Or is it a bug?

I use atom 1.40.1 and docblock 0.15.0.

**Comment by spadarian** [comment]
Thanks and sorry for the late reply.

Let me know if that fixed the problem.

**Comment by oliver-joos** [comment]
Great! Thank you!
I confirm that style "sphinx" now works as expected in 0.15.1.
