### ISSUE TITLE
issue generating docblock when class doesn't have __init__() fn

### ISSUE THREAD

**Issue by pschiffe** [spadarian/docblock-python#47]
Hello,

first of all, thanks for a very fine atom package!

I've noticed the following issue, when a python class is missing a `__init__()` fn. In the following example I've generated docblock in the same way for both classes. The first one was generated correctly according to my settings:
```
class AA:
    '''Short summary.

    Attributes
    ----------
    attr1 : type
        Description of attribute `attr1`.
    attr2 : type
        Description of attribute `attr2`.

    '''
    attr1 = 1
    attr2 = 2

    def __init__(self):
        return True

    def f1(self):
        return True


class BB:
    """Short summary."""
    attr1 = 1
    attr2 = 2

    def f1(self):
        return True
```

**Comment by pschiffe** [comment]
Thank you!

**Comment by spadarian** [comment]
You are welcome. Thanks for reporting the issue!
